"""Unattended scheduled monitoring across the monitored portfolio.

Closes the gap DECISIONS.md records as still open ("FR-004 ... and
FR-019 ... remain unfulfilled for the V2 multi-company model"): the
scheduler fired on time, but the job it ran was V2's single-target
`run_workflow()`, which researches `settings.target_company` - a demo
placeholder. Every automatic run analysed that placeholder and no
monitored company was ever covered by one.

A scheduled run now drives the same V3 per-company pipeline the UI's Run
Scout / Refresh Intelligence actions drive
(backend/orchestration/manual_analysis.py), once per monitored company.
That pipeline is what actually produces the opportunities, refresh
snapshots and notifications the dashboard shows, so ADR-012 ("manual
analysis reuses the exact same service functions scheduled monitoring
would use, so both paths stay behaviorally identical") is now true in
both directions rather than only on paper.

Three deliberate choices, all recorded in TECH_DEBT.md:

- **Refresh, not publish.** Each company goes through
  `refresh_company_intelligence()` - the full pipeline minus
  ReportingStage. An unattended daily pass over the whole portfolio that
  published a Report per company would append one report per company per
  day that nobody asked for, which is the exact side effect the
  refresh/publish split was introduced to stop. Notifications are
  generated by the pipeline either way, so alerting is unaffected.
- **One workflow-history row per company.** Each company's outcome is
  saved through `report_storage.save_report()` as its own WorkflowState,
  so `/workflow/history` and the System Status page keep answering "what
  ran, against which company, and did it work" - which was the only
  visible record a scheduled run ever left.
- **Failure is per company.** FR-020 ("failure for one company shall not
  stop processing of remaining companies") is why every company's run,
  and its history write, is individually guarded.
"""

import asyncio
import logging
from typing import Optional

from backend.models.company import Company
from backend.orchestration.manual_analysis import refresh_company_intelligence
from backend.report_storage import save_report
from backend.services import company_service
from backend.workflow.state import WorkflowState

logger = logging.getLogger(__name__)

STAGE_NAME = "scheduled_monitoring"


def _is_monitored(company: Company) -> bool:
    """The definition of "in the portfolio": monitoring switched on and
    not archived. `monitoring_status` is a string, not a bool, per
    DATA_MODEL.md - see backend/models/company.py.
    """
    return company.monitoring_status == "enabled" and company.archived_at is None


def select_target_companies(target_company_ids: Optional[list[str]] = None) -> list[Company]:
    """Resolves which companies a scheduled run should cover.

    An empty/absent `target_company_ids` means "every monitored company",
    which is both the fallback job's behavior (no Schedule rows exist)
    and what a Schedule with no explicit targets means - the
    Administration UI already renders that case as "all companies", so
    the two agree.

    An explicit list is filtered against the same monitored set rather
    than trusted: a Schedule can outlive the company it names, or name
    one that has since been archived or had monitoring switched off, and
    silently researching it anyway would defeat the switch that turned it
    off. Skipped ids are logged rather than raising - one stale id must
    not cancel the whole run.
    """
    monitored = [c for c in company_service.list_companies() if _is_monitored(c)]

    if not target_company_ids:
        return monitored

    by_id = {company.id: company for company in monitored}
    selected = []
    for company_id in target_company_ids:
        company = by_id.get(company_id)
        if company is None:
            logger.warning(
                "Scheduled run skipping company %s: it no longer exists, is archived, "
                "or has monitoring disabled.",
                company_id,
            )
            continue
        selected.append(company)
    return selected


async def _run_for_company(company: Company) -> WorkflowState:
    """Runs one company and records the outcome, whatever it is.

    Returns rather than raises: the caller is a loop over the portfolio,
    and this function's whole purpose is that one company's failure stays
    that one company's failure.
    """
    state = WorkflowState(
        status="running", current_stage=STAGE_NAME, target_company=company.name
    )
    try:
        result = await refresh_company_intelligence(company)
    except Exception as exc:  # noqa: BLE001 - FR-020: the next company must still run
        logger.exception(
            "Scheduled run failed for company %s (%s).", company.name, company.id
        )
        state.status = "failed"
        state.errors.append(f"Scheduled monitoring for {company.name}: {exc}")
    else:
        state.status = "completed"
        state.completed_stages = [STAGE_NAME]
        state.reporting_output = {
            "company_id": company.id,
            "triggered_by": "schedule",
            # False on purpose - see this module's docstring. Stated in
            # the record so "why is there no report for last night's run"
            # is answerable from the history row itself.
            "published_report": False,
            "refresh_summary": result.refresh_summary,
        }

    try:
        await asyncio.to_thread(save_report, state)
    except Exception:  # noqa: BLE001 - a lost history row must not cost the remaining companies
        logger.exception(
            "Could not record the scheduled run for company %s (%s); the analysis itself "
            "already ran.",
            company.name,
            company.id,
        )
    return state


async def run_scheduled_monitoring(
    target_company_ids: Optional[list[str]] = None,
) -> list[WorkflowState]:
    """One scheduled pass over the selected companies, sequentially.

    Sequential rather than concurrent, matching DECISIONS.md's "Workflow
    is sequential": each company's run makes several LLM calls, and
    firing the whole portfolio at a provider at once is a rate-limit
    incident, not a speed-up.
    """
    companies = await asyncio.to_thread(select_target_companies, target_company_ids)

    if not companies:
        logger.warning(
            "Scheduled run has no monitored companies to analyse - nothing to do. "
            "Add a company, or re-enable monitoring on an existing one."
        )
        return []

    logger.info(
        "Scheduled run starting for %d monitored compan%s.",
        len(companies),
        "y" if len(companies) == 1 else "ies",
    )

    states = [await _run_for_company(company) for company in companies]

    failed = [state for state in states if state.status != "completed"]
    logger.info(
        "Scheduled run finished: %d of %d compan%s completed.",
        len(states) - len(failed),
        len(states),
        "y" if len(states) == 1 else "ies",
    )
    return states
